todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/',views.addTodoView), 
    path('deleteTodoItem/<int:i>/', views.deleteTodoView), 
] 

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls',)),
]

todoapp/models.py
from django.db import models


# Create your models here.
class TodoListItem(models.Model):
    content = models.TextField()
    priority = models.TextField() 
    date1=models.DateField(auto_now_add=True)


#create your date models here.

todoapp/views.py
from django.shortcuts import render
from .models import TodoListItem 
from django.http import HttpResponseRedirect 
# Create your views here.
def index(request):
    return render(request, 'index.html')



def todoappView(request):
    all_todo_items = TodoListItem.objects.all()
    return render(request, 'todolist.html',  {'all_items':all_todo_items})


def addTodoView(request):
    # x = request.POST.get('todotext')
    new_item = TodoListItem()
    new_item.content = request.POST.get('content')
    new_item.date1 = request.POST.get('date1')
    new_item.priority = request.POST.get('priority')
    
    new_item.save()
    return HttpResponseRedirect('/todo/') 

def deleteTodoView(request, i):
    y = TodoListItem.objects.get(id= i)
    y.delete()
    return HttpResponseRedirect('/todo/') 

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>TO DO LIST SITE</title>
</head>

<div class="container">
    <div class="row">
      <img src="{% static 'img/todo1.png' %}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 300px; height: 300px;">
    </div>
    <div class="card text-center" style="margin-top: 40px;">
        <div class="card-body">
          <h3 class="card-title">Welcome to the TO-DO LIST App</h3>
          <h6>Start Making!!</h3>
          <br>
          <br>
          <a href="{% url 'todoapp:todo' %}" class="btn btn-info tn-rounded">GENERAL TO DO LIST</a>

         
        </div>
      </div>
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

templates/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    
<div class="container">
<!-- 
    <div class="row">
        <form action="/addTodoItem/" method = "post">
            {% csrf_token %}
            <input type="text" name="content">
            <input type="submit" value="Add Todo Item">
        </form> 
    </div>

    <div class="row">
        <ul>
            {% for i in all_items %} 
            <li>{{i.content}}
            </li>
            <form action="/deleteTodoItem/{{i.id}}/" method = "post">{% csrf_token %}
                <input type="submit" value="Delete">
    </form> 
            {% endfor %}
        </ul> 
    </div>
 -->

    
    <div class="row" style="margin-top: 20px;">
        <div class="col">

            <div class="row">
                <form class="form-inline" action="/addTodoItem/" method = "post">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-7">
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="content" class="sr-only"></label>
                                <input type="text" class="form-control" name="content" placeholder="Research">
                              </div>
                        </div>
                       
                        <div class="col-8">
                            <div class="form-group mx-sm-3 mb-2">
                                <form action="/action_page.php">
                                    <label for="priority">Importance</label>
                                    <select name="priority" id="priority">
                                      <option value="Urgent">Urgent</option>
                                      <option value="General">General</option>
                                      <option value="Occasional">Occasional</option>
                                    </select>
                                    <br><br>
                                    </form>
                                
                              </div>
                       
                        <div class="col-4" style="margin-top: 25px;">
                            <button type="submit" class="btn btn-success btn-rounded">ADD TO DO ITEMS</button>
                        </div>
                    </div>
                    
                </form>
                    
                  
            </div>
            {% for i in all_items %} 
            <div class="row">
                <div class="col-1"></div>
                <div class="col-6">
                    <div class="card  text-white bg-dark mb-3">
                        <div class="card-body">
                            {{i.priority}} 


                        </div>
                        <div class="card-body">
                            {{i.content}}

                        </div>
                        <div class="card-body">
                            {{i.date1}}

                        </div>
                      </div>
                </div>

                <div class="col-2">
                    <form action="/deleteTodoItem/{{i.id}}/" method = "post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                          </svg></i>
                        </button>
            </form> 
                </div>
                <div class="col-3"></div>
            </div>
            {% endfor %}
        </div>
    </div>
    


</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>